### ISSUE TITLE
[atomWithHash] When returning to the first screen with history.back, the atom value is not initialized.

### ISSUE THREAD

**Issue by jakkku** [jotai-labs/jotai-location#3]
## Summary
If I go back to the first screen with no hash, `hashchange` event will not fire.  
So, the atom value is not initialized.

I think we can use `popstate` instead of `hashchange`.
The `popstate` will fire even if the hash does not change, but I think it is okay because `setAtom` compares the previous data with the next data.

Please let me know if there is something I am not thinking of.

## Link to reproduction
Here is the [codesandbox](https://codesandbox.io/s/jotai-atomwithhash-issue-63vhnq?file=/src/App.tsx).

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by jakkku** [comment]
actually I didn't know that.
I just saw `atomWithHash` that is based on `hashchange`.
https://github.com/jotai-labs/jotai-location/blob/43f9b94ab19cacbf8af3d199a7ec6c271c84ca86/src/atomWithHash.ts#L39-L41

**Comment by dai-shi** [comment]
> I just saw `atomWithHash` that is based on `hashchange`.

Yeah, `hashchange` is the whole idea behind `atomWithHash`.
For `popstate`, I created `atomWithLocation`.

It's a bit weird design to use `popstate` in `atomWithHash`. Can't be helped, if it's a weird browser behavior.

**Comment by jakkku** [comment]
> Can't be helped, if it's a weird browser behavior.

Yeah, That's right!
thank you

**Comment by dai-shi** [comment]
Yeah, let's revisit it when we get more feedback.
